apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway-deployment
    labels: 
        app: web
spec:
    replicas: 1
    selector:
        matchLabels:
            app: web
            micro-service: gateway
    template:
      metadata:
        name: gateway-pod
        labels:
          app: web
          micro-service: gateway
      spec:
        containers:
          - name: gateway
            image: docker.io/dev1911/drone_plus_plus_gateway:latest
            ports:
              - containerPort: 8000