apiVersion: v1
kind: Service
metadata:
    name: gateway-service
    labels:
        micro-service: gateway
spec:
    type: NodePort
    selector:
        app: web
        micro-service: gateway
    ports:
        - nodePort: 30002
          port: 9000
          targetPort: 8000