apiVersion: v1
kind: Service
metadata:
    name: redis-service
    labels:
        micro-service: redis
spec:
    selector:
        app: streaming
        micro-service: redis
    ports:
        - port: 6379
          targetPort: 6379