apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: streaming
    micro-service: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379