version: '3'

services:
  web:
    build: .
    command: sh -c "python user/manage.py makemigrations && python user/manage.py migrate && python user/manage.py runserver 0.0.0.0:8001"
    container_name: user
    volumes:
      - .:/code
    ports:
      - "8001:8001"