# Generated by Django 2.1.7 on 2020-02-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=256)),
                ('battery', models.FloatField()),
                ('curr_battery', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Idle', 'Idle'), ('Charging', 'Charging'), ('Delivering', 'Delivering'), ('Returning', 'Returning'), ('Offline', 'Offline')], max_length=10)),
                ('curr_latitude', models.FloatField(blank=True, null=True)),
                ('curr_longitude', models.FloatField(blank=True, null=True)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse')),
            ],
        ),
    ]
