# Generated by Django 2.2.3 on 2020-02-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200219_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Error', 'Error'), ('Ongoing', 'Ongoing')], default='Pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.FloatField(max_length=20),
        ),
    ]
