# Generated by Django 2.2.3 on 2020-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('drone_id', models.IntegerField(blank=True, null=True)),
                ('order_name', models.CharField(default='Some Order', max_length=300)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Error', 'Error'), ('Ongoing', 'Ongoing')], default='Pending', max_length=20)),
            ],
        ),
    ]
