apiVersion: v1
kind: Pod
metadata:
    name: logistics
    labels:
        app: web
        micro-service: logistics
spec:
    containers:
        - name: logistics-django-app
          image: docker.io/dev1911/drone_plus_plus_logistics:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: logistics