apiVersion: v1
kind: Service
metadata:
    name: logistics-service
    labels:
        micro-service: logistics
spec:
    type: NodePort
    selector:
        app: web
        micro-service: logistics
    ports:
        - nodePort: 30003
          port: 9000
          targetPort: 8000