apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-logistics-pvc
    labels:
        type: local
        micro-service: logistics
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi