apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-logistics-deployment
  labels:
    app: postgres
    micro-service: logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      micro-service: logistics
  template:
    metadata:
      name: postgres-logistics-pod
      labels:
        app: postgres
        micro-service: logistics
        type: database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: admin
          - name: POSTGRES_DB
            value: logistics
          volumeMounts:
          - name: postgres-logistics-pv
            mountPath: var/lib/postgresql/data1
      volumes:
      - name: postgres-logistics-pv
        persistentVolumeClaim:
            claimName: postgres-logistics-pvc