apiVersion: v1
kind: Service
metadata:
    name: postgres-logistic
    labels:
      micro-service: logistics
spec:
    selector:
      app: postgres
      micro-service: logistics
    ports:
      - protocol: TCP
        port: 8001
        targetPort: 5432
    type: NodePort