apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        micro-service: order
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql-pod
            micro-service: order
    template:
        metadata:
            name: mysql-pod
            labels:
                app: mysql-pod
                micro-service: order
        spec:
            containers:
            - name: mysql
              image: mysql:latest
              env:
                - name: MYSQL_ROOT_USER
                  value: root
                - name: MYSQL_ROOT_PASSWORD
                  value: admin
                - name: MYSQL_DB
                  value: order
              args: ["--default-authentication-plugin=mysql_native_password"]
              ports:
                - containerPort: 3306
              volumeMounts:
              - name: mysql-pv
                mountPath: /mnt/data
            volumes:
            - name: mysql-pv
              persistentVolumeClaim:
                claimName: mysql-pvc 