apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        micro-service: order
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql-pod
            micro-service: order
    template:
        metadata:
            name: mysql-pod
            labels:
                app: mysql-pod
                micro-service: order
        spec:
            containers:
                - name: mysql
                  image: mysql:latest
                  env:
                    # - name: MYSQL_USER
                    #   valueFrom:
                    #     secretKeyRef:
                    #         name: mysql-credentials
                    #         key: user
                    # - name: MYSQL_ROOT_PASSWORD
                    #   valueFrom:
                    #     secretKeyRef:
                    #         name: mysql-credentials
                    #         key: password
                    # - name: MYSQL_DB
                    #   value: main_order
                    - name: MYSQL_ROOT_PASSWORD
                      value: admin
                  volumeMounts:
                  - name: mysql-pv
                    mountPath: /var/lib/mysql
            volumes:
                - name: mysql-pv
                  persistentVolumeClaim:
                    claimName: mysql-pvc