apiVersion: v1
kind: Pod
metadata:
    name: mysql
    labels:
        app: mysql
        micro-service: order
        type: database
spec:
    containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DB
              value: order
            - name: MYSQL_ROOT_USER
              value: admin
          ports:
            - containerPort: 3306
    #       volumeMounts:
    #       - name: mysql-pv
    #         mountPath: /var/lib/mysql
    # volumes:
    # - name: mysql-pv
    #   persistentVolumeClaim:
    #     claimName: mysql-pvc 