apiVersion: v1
kind: Pod
metadata:
    name: mysql
    labels:
        app: mysql
        micro-service: order
        type: database
spec:
    containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DB
              value: order
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: mysql-pv
            mountPath: /mnt/data
    volumes:
    - name: mysql-pv
      persistentVolumeClaim:
        claimName: mysql-pvc 