apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-deployment
    labels: 
        app: web
spec:
    replicas: 2
    selector:
        matchLabels:
            micro-service: order
    template:
        metadata:
            labels:
                app: web
                micro-service: order
        spec:
            containers:
                - name: order-django-app
                  image: docker.io/dev1911/drone_plus_plus_order
                  ports:
                    - containerPort: 8000
                    