apiVersion: v1
kind: Pod
metadata:
    name: order
    labels:
        app: web
        micro-service: order
spec:
    containers:
        - name: order-django-app
          image: docker.io/dev1911/drone_plus_plus_order
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_PORT
              value: 8001