apiVersion: v1
kind: Pod
metadata:
    name: mysql-user
    labels:
        app: mysql
        micro-service: user
        type: database
spec:
    containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: user
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: admin
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: mysql-user-pv
            mountPath: /var/lib/mysql
    volumes:
    - name: mysql-user-pv
      persistentVolumeClaim:
        claimName: mysql-user-pvc 