apiVersion: v1
kind: Service
metadata:
    name: postgres-user
    labels:
      micro-service: user
spec:
    selector:
      app: postgres
      micro-service: user
    ports:
      - protocol: TCP
        port: 8001
        targetPort: 5432
    type: NodePort