apiVersion: v1
kind: Service
metadata:
    name: user-service
    labels:
        micro-service: user
spec:
    type: NodePort
    selector:
        app: web
        micro-service: user
    ports:
        - nodePort: 30001
          port: 9000
          targetPort: 8000