apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
    labels:
        type: local
        micro-service: user
spec:
    storageClassName: manual
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data_user/"