apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc
    labels:
        type: local
        micro-service: user
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi