apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
      micro-service: order
spec:
    selector:
      app: mysql
      micro-service: order
    ports:
      - protocol: TCP
        port: 8001
        targetPort: 3306
    type: NodePort