apiVersion: v1
kind: Service
metadata:
    name: order-service
    labels:
        micro-service: order
spec:
    type: NodePort
    selector:
        app: web
        micro-service: order
    ports:
        - nodePort: 30000
          port: 9000
          targetPort: 8000